"""Add is_verified to User

Revision ID: 8895ec8b9051
Revises: 29b8be1fb69e
Create Date: 2025-04-21 20:41:32.314796

"""
from alembic import op
import sqlalchemy as sa
# --- Added import ---
from sqlalchemy.sql import expression
# --- End Added import ---


# revision identifiers, used by Alembic.
revision = '8895ec8b9051'
down_revision = '29b8be1fb69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # --- Modified line below ---
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=expression.false()))
        # --- End Modified line ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###